"""Add response_text column to emergencies table

Revision ID: 33e471b932ae
Revises: 434a71e8b557
Create Date: 2024-11-22 11:13:04.476045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e471b932ae'
down_revision: Union[str, None] = '434a71e8b557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergencies', sa.Column('response_text', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergencies', 'response_text')
    # ### end Alembic commands ###
